name = "SimpleLockFiles"
uuid = "0c975e61-21d9-4454-8de5-ff08fd2c478f"
authors = ["josePereiro <jose.pereiro.lab@gmail.com> and contributors"]
version = "0.4.1"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
